name: x2trivia
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any
  bloc: ^8.1.0
  fluttertoast: ^8.2.4

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  collection: ^1.18.0
  cloud_firestore: ^4.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true

  uses-material-design: true
